### ISSUE TITLE
Impossible for listeners creation

### ISSUE THREAD

**Issue by morpheeD** [adaptivethreat/Empire#327]
## Empire Version
1.6

## OS Information (Linux flavor, Python version)
Debian 8.2

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When i install a new empire on a new VM and i tried to create a listeners il send me this

(Empire: listeners) > set Port 1234
(Empire: listeners) > run
[!] Error starting listener on port 1234: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 1234, port likely already in use.
(Empire: listeners) > set Host ip
(Empire: listeners) > run
[!] Error starting listener on port 1234: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 1234, port likely already in use.
(Empire: listeners) > set Port 6667
(Empire: listeners) > run
[!] Error starting listener on port 6667: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 6667, port likely already in use.
(Empire: listeners) > set Port 16667
(Empire: listeners) > run
[!] Error starting listener on port 16667: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 16667, port likely already in use.
(Empire: listeners) >

**Comment by atkinsj** [comment]
I see the same behaviour when you attempt to set the Host field of the listener to an IP address that is not on the local machine. This never used to be the case as the listener would bind to 0.0.0.0 and the Host field would only be used for the stager generation; this has changed at some point in the last few months.

This is particularly notable on EC2 where the local machine IP address is a 172. and you need to configure the Host with the public address.

**Comment by morpheeD** [comment]
for information is work when i use the DNS but when i use the IP no

**Comment by mynameisv** [comment]
Hi,
I may be wrong but in fact this is not a bug ;-)

As you can see in the source code (http.py:EmpireServer), the listener listen on the IP set in "lhost", so if you give an IP that's not configured on your server's local interfaces, it won't work.
For example :
You have a NAT and your server is addressed with a private IP
{ Internet }----{ Your public IP, 1.2.3.4 }---{ Some router/firewall doing the NAT }---{ Empire, with a private IP : 10.0.13.37 }
Configuring a listener with the public IP 1.2.3.4 won't work because you server's system does not know this ip/interface.

So to make it work, you have two main solutions :
 - The easiest one -> decode your stager, change the ip, re-encode
 - The "u-won't-have-it-before-long-time" one : Pull a request to add an option in the stager to user another IP than the listeners'one ;-)


To decode/reencode, you use the following code (sorry if there are problems with indentation, i hate python for that and sorry if there are bugs ^_^) :

import base64
import sys
def DecReenc(stagerBase64, ipNew):
  #decode your base64 encoded stager
  stagerUnicode = base64.b64decode(stagerBase64)
  #a way to remove the \0x00
  stagerAscii = ""
  for i in range (0,len(stagerUnicode)):
    if (i%2==0):
      stagerAscii+=stagerUnicode[i]
  #ip address position may change...
  tag1 = '("http://'
  tag2 = ':'
  ipos1 = stagerAscii.find(tag1)
  if ipos1==-1:
    print "Error finding the IP address, tag="+tag1
    sys.exit()
  
  ipos2 = stagerAscii.find(tag2, ipos1+len(tag1))
  if ipos2==-1:
    print "Error finding the IP address, tag="+tag2
    sys.exit()
 
  stagerNew = stagerAscii[0:ipos1+len(tag1)]+ipNew+stagerAscii[ipos2:]
  stagerNewB64 = base64.b64encode("".join([char + "\x00" for char in unicode(stagerNew)]))
  return stagerNewB64
# - DecReenc() - end

 
# set up here your stager
stagerBase64 = raw_input("Paste your base64 encoded stager here: ")
# set up here your ip
ipNew = raw_input("Type your ip address here: ")
stagerNew = DecReenc(stagerBase64, ipNew)
stagerNew

**Comment by atkinsj** [comment]
@mynameisv I appreciate the response but that is very unnecessary. Empire specifically has both the 'host' and 'port' options to account for this: Host is for the stager and Port is for the Empire C2 (intended to listen on 0.0.0.0:Port) which is a *much* more elegant solution than modifying the stager code.

I'll try and dig through the source later to pull out the offending commit.

**Comment by mynameisv** [comment]
Hi, 
again i may be wrong, but port is for port, and host for host :-)
If you specify an IP address in the option "Host" (Empire: listeners), it'll be use for the local listening socket and also the stager. Maybe i'm missing lines in the source code ;-)
Here's what i read : 
```
listeners.py->
513:     def add_listener_from_config(self):
...
519:        host = self.options['Host']['Value'] <= we get the Option "Host" for the stager and also the TCP socket listener
520:        port = self.options['Port']['Value'] <= we get the Option "Port", for the TCP socket listener
...
567:                lhost = http.host2lhost(host) <= ipv4 checker
569:                server = http.EmpireServer(self.agents, lhost=lhost, port=port, cert=certPath) <= we use "lhost" as it is and it's the same behavior for "port"
```
```
http.py->
147:class EmpireServer(threading.Thread):
...
155:    def __init__(self, handler, lhost='0.0.0.0', port=80, cert=''): <= by default, ip is 0.0.0.0 if unspecified
...
164:            self.server = BaseHTTPServer.HTTPServer((lhost, int(port)), RequestHandler) <= we create an HTTP server with lhost IP address if specified, if not it is 0.0.0.0
```
In the class documentation, HTTPServer's first parameter is a tuple of (IP address, TCP port):
```
def run(server_class=BaseHTTPServer.HTTPServer,
        handler_class=BaseHTTPServer.BaseHTTPRequestHandler):
    server_address = ('', 8000)
    httpd = server_class(server_address, handler_class)
    httpd.serve_forever()
class BaseHTTPServer.HTTPServer(server_address, RequestHandlerClass)

    This class builds on the TCPServer class by storing the server address as instance variables named server_name and server_port. The server is accessible by the handler, typically through the handler’s server instance variable.
```

**Comment by mynameisv** [comment]
This answer is for the part you added in your comment : <<This worked as intended until recently when it looks @HarmJ0y and @n0clues fixed #175 in commit f376dc2 ... edge case and that doesn't appear to be working.>>

Yes, it's a change from previous version. It needs a stager modification to work with NAT or a new option like HostNat :-)

**Comment by gh0st-r7** [comment]
I'm with the original poster of this issue. I use to run Empire from my house behind a NAT and just use port forwarding. I would set my "Host" in the stager to http://[OutsideIP]:8080 and it would work. Now if I set my Host to my router IP (which worked before) and run it, I get a "Error starting listener... Cannot assign address.

**Comment by PandoraSec** [comment]
i have the same problem, it is a bug? anyone have find a solution?

**Comment by HarmJ0y** [comment]
Can you try the 2.0_beta branch? BindIP is separated out from the Host, which should hopefully fix this issue.

**Comment by gh0st-r7** [comment]
It's the same for the 2.0 beta branch. It gives an error as well. It last worked for version 1.5 as [seen here](http://imgur.com/P9Azd5n). 
Version 1.6 and above has that error as [seen here](http://imgur.com/urfQFsm).

**Comment by atkinsj** [comment]
The fix in the 2.0 beta branch works fine for me with BindIP defaulting to 0.0.0.0.

**Comment by skuta** [comment]
Can we have some hotfix on this? =/ I'd download 1.5 if there was a place to do so :-)

**Comment by danielsan29** [comment]
works fine for me too

**Comment by retbandit** [comment]
Just assign a public DNS record associated with the public IP for the Host instead of using public IP

**Comment by enigma0x3** [comment]
It should work in 2.0. Let us know if not.

Thanks
