### ISSUE TITLE
empire doesn't let me set my public ip

### ISSUE THREAD

**Issue by HackM3nt3** [adaptivethreat/Empire#407]
i can't use empire to wan testing with my public ip.

Empire: listeners) > set Host 181.61.227.235
(Empire: listeners) > execute
[!] Error starting listener on port 443: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 443, port likely already in use.

**Comment by leechristensen** [comment]
Empire cannot bind to an IP that is not on the current host, or when the port is already in use.

Is the machine Empire running connected directly to the internet (i.e. if you do an "ifconfig" do you see your public IP listed?)?  If it is not listed, you will either need to connect directly to the internet or forward the port to your NAT'ed address.  If it is listed, verify that port 443 is not already in use by running "netstat -ntlp | grep ":443" and ensure that that nothing returns prior to starting Empire.  If netstat reports that something is already listening on that port, you will need to kill/stop that program.

**Comment by fEDUntu** [comment]
I've got some troubles too when I was trying to set up Empire over the Internet.
I deployed my C&C server on Amazon AWS for my tests and I failed when I tried to set up the public IP for the listener. The following error appears:
_[!] Error starting listener on port 443: [Errno 99] Cannot assign requested address
[!] Error starting listener on port 443, port likely already in use._

**The workaround I used is the public DNS that Amazon AWS provides, instead of public IP.** 
Maybe can be usefull for someone else.
